export const SCOPE_TYPES = Object.freeze(["global", "group", "team", "event", "own_records"]);

export const ACCOUNT_STATUSES = Object.freeze(["invited", "active", "disabled", "suspended", "archived"]);

export const ROLE_KEYS = Object.freeze({
  CHIEF: "chief",
  MEDIA_CONTRIBUTOR: "media_contributor",
  MEDIA_MANAGER: "media_manager",
  FINANCE_VIEWER: "finance_viewer",
  FINANCE_CONTRIBUTOR: "finance_contributor",
  FINANCE_APPROVER: "finance_approver",
  STORAGE_ASSISTANT: "storage_assistant",
  STORAGE_MANAGER: "storage_manager",
  FORMS_MANAGER: "forms_manager",
  CONTENT_APPROVER: "content_approver",
  ACCESS_ADMINISTRATOR: "access_administrator",
  SYSTEM_ADMINISTRATOR: "system_administrator"
});

export const TEAM_KEYS = Object.freeze({
  MEDIA: "media",
  FORMS: "forms",
  EVENTS: "events",
  WEBSITE: "website",
  FINANCE: "finance",
  STORAGE: "storage"
});

export const PERMISSIONS = Object.freeze({
  DASHBOARD_ACCESS: "dashboard.access",
  NOTIFICATIONS_VIEW: "notifications.view",
  AI_USE: "ai.use",

  GROUPS_VIEW_ASSIGNED: "groups.view_assigned",
  GROUPS_MANAGE: "groups.manage",
  SCOUTS_VIEW: "scouts.view",
  SCOUTS_CREATE: "scouts.create",
  SCOUTS_UPDATE: "scouts.update",
  SCOUTS_MOVE_GROUP: "scouts.move_group",
  SCOUTS_ARCHIVE: "scouts.archive",
  SCOUTS_EXPORT: "scouts.export",
  REGISTERED_SCOUTS_UPLOAD: "registered_scouts.upload",

  ATTENDANCE_VIEW: "attendance.view",
  ATTENDANCE_RECORD: "attendance.record",
  ATTENDANCE_CORRECT: "attendance.correct",
  ATTENDANCE_DELETE_SESSION: "attendance.delete_session",
  ATTENDANCE_EXPORT: "attendance.export",
  CHIEF_ATTENDANCE_VIEW: "chief_attendance.view",
  CHIEF_ATTENDANCE_MANAGE: "chief_attendance.manage",
  EQUIPES_VIEW: "equipes.view",
  EQUIPES_CREATE: "equipes.create",
  EQUIPES_UPDATE: "equipes.update",
  EQUIPES_ASSIGN_SCOUTS: "equipes.assign_scouts",
  EQUIPES_DELETE: "equipes.delete",

  FORMS_FILL: "forms.fill",
  FORMS_VIEW_OWN_SUBMISSIONS: "forms.view_own_submissions",
  FORMS_CREATE: "forms.create",
  FORMS_TEMPLATES_VIEW: "forms.templates.view",
  FORMS_TEMPLATES_MANAGE: "forms.templates.manage",
  FORMS_POST_REQUEST: "forms.post.request",
  FORMS_POST_APPROVE: "forms.post.approve",
  FORMS_CLOSE: "forms.close",
  FORMS_REOPEN: "forms.reopen",
  FORMS_RESPONSES_VIEW_GROUP: "forms.responses.view_group",
  FORMS_RESPONSES_VIEW_ALL: "forms.responses.view_all",
  FORMS_RESPONSES_EXPORT: "forms.responses.export",
  FORMS_DELETE_POSTED: "forms.delete_posted",

  CALENDAR_VIEW: "calendar.view",
  CALENDAR_CREATE_GROUP_EVENT: "calendar.create_group_event",
  CALENDAR_CREATE_PUBLIC_EVENT: "calendar.create_public_event",
  CALENDAR_UPDATE_OWN: "calendar.update_own",
  CALENDAR_UPDATE_ALL: "calendar.update_all",
  CALENDAR_APPROVE: "calendar.approve",
  CALENDAR_DELETE: "calendar.delete",

  CONTENT_CREATE: "content.create",
  CONTENT_SUBMIT: "content.submit",
  CONTENT_EDIT_OWN: "content.edit_own",
  CONTENT_EDIT_ALL: "content.edit_all",
  CONTENT_APPROVE: "content.approve",
  CONTENT_PUBLISH: "content.publish",
  CONTENT_DELETE: "content.delete",
  MEDIA_VIEW: "media.view",
  MEDIA_UPLOAD: "media.upload",
  MEDIA_EDIT_OWN: "media.edit_own",
  MEDIA_EDIT_ALL: "media.edit_all",
  MEDIA_APPROVE: "media.approve",
  MEDIA_PUBLISH: "media.publish",
  MEDIA_DELETE: "media.delete",
  ALBUMS_CREATE: "albums.create",
  ALBUMS_MANAGE: "albums.manage",

  FINANCE_VIEW: "finance.view",
  FINANCE_CREATE_TRANSACTION: "finance.create_transaction",
  FINANCE_EDIT_OWN_TRANSACTION: "finance.edit_own_transaction",
  FINANCE_EDIT_ALL_TRANSACTIONS: "finance.edit_all_transactions",
  FINANCE_UPLOAD_RECEIPT: "finance.upload_receipt",
  FINANCE_APPROVE_TRANSACTION: "finance.approve_transaction",
  FINANCE_EXPORT: "finance.export",
  FINANCE_MANAGE_CATEGORIES: "finance.manage_categories",
  FINANCE_MANAGE_SETTINGS: "finance.manage_settings",

  STORAGE_VIEW: "storage.view",
  STORAGE_CREATE_ITEM: "storage.create_item",
  STORAGE_UPDATE_ITEM: "storage.update_item",
  STORAGE_ISSUE_ITEMS: "storage.issue_items",
  STORAGE_RECORD_RETURNS: "storage.record_returns",
  STORAGE_ADJUST_QUANTITY: "storage.adjust_quantity",
  STORAGE_WRITE_OFF: "storage.write_off",
  STORAGE_AUDIT: "storage.audit",
  STORAGE_EXPORT: "storage.export",
  STORAGE_MANAGE_CATEGORIES: "storage.manage_categories",

  DOCUMENTS_VIEW: "documents.view",
  DOCUMENTS_UPLOAD: "documents.upload",
  DOCUMENTS_EDIT: "documents.edit",
  DOCUMENTS_DELETE: "documents.delete",
  DOCUMENTS_MANAGE_PERMISSIONS: "documents.manage_permissions",
  REPORTS_VIEW: "reports.view",
  REPORTS_GENERATE: "reports.generate",
  REPORTS_EXPORT: "reports.export",
  ARCHIVED_YEARS_VIEW: "archived_years.view",
  ARCHIVED_YEARS_MANAGE: "archived_years.manage",

  CONTACT_MESSAGES_VIEW: "contact_messages.view",
  CONTACT_MESSAGES_RESPOND: "contact_messages.respond",
  CONTACT_MESSAGES_ARCHIVE: "contact_messages.archive",
  CONTACT_MESSAGES_DELETE: "contact_messages.delete",
  WEBSITE_CONTENT_VIEW: "website_content.view",
  WEBSITE_CONTENT_EDIT: "website_content.edit",
  WEBSITE_CONTENT_APPROVE: "website_content.approve",

  USERS_VIEW: "users.view",
  USERS_INVITE: "users.invite",
  USERS_UPDATE_PROFILE: "users.update_profile",
  USERS_DISABLE: "users.disable",
  USERS_REACTIVATE: "users.reactivate",
  USERS_RESET_PASSWORD: "users.reset_password",
  USERS_DELETE: "users.delete",
  USERS_REVOKE_SESSIONS: "users.revoke_sessions",
  USERS_ASSIGN_ROLES: "users.assign_roles",
  USERS_ASSIGN_GROUPS: "users.assign_groups",
  USERS_ASSIGN_TEAMS: "users.assign_teams",
  ROLES_VIEW: "roles.view",
  ROLES_CREATE: "roles.create",
  ROLES_UPDATE: "roles.update",
  ROLES_DELETE: "roles.delete",
  PERMISSIONS_MANAGE: "permissions.manage",
  AUDIT_LOGS_VIEW: "audit_logs.view",
  SYSTEM_SETTINGS_VIEW: "system_settings.view",
  SYSTEM_SETTINGS_MANAGE: "system_settings.manage"
});
