-- Immutable Finance/Storage cross-domain references.
BEGIN;
CREATE TABLE IF NOT EXISTS public.finance_storage_links(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source_workspace text NOT NULL CHECK(source_workspace IN ('finance','storage')),source_type text NOT NULL,source_id uuid NOT NULL,target_workspace text NOT NULL CHECK(target_workspace IN ('finance','storage')),target_type text NOT NULL,target_id uuid NOT NULL,link_type text NOT NULL CHECK(link_type IN ('restock_purchase','delivery_expense','damage_charge','asset_purchase','borrower_charge')),idempotency_key text NOT NULL UNIQUE,created_by uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),CHECK(source_workspace<>target_workspace),UNIQUE(source_workspace,source_type,source_id,target_workspace,target_type,target_id,link_type));
ALTER TABLE public.finance_storage_links ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "authorized users read finance storage links" ON public.finance_storage_links;
CREATE POLICY "authorized users read finance storage links" ON public.finance_storage_links FOR SELECT TO authenticated USING(public.has_permission('finance.workspace.access') OR public.has_permission('storage.workspace.access'));
CREATE OR REPLACE FUNCTION public.link_finance_storage_resource(source_workspace text,source_type text,source_id uuid,target_workspace text,target_type text,target_id uuid,link_type text,idempotency_key text) RETURNS public.finance_storage_links LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ DECLARE saved public.finance_storage_links;BEGIN IF source_workspace=target_workspace OR source_workspace NOT IN ('finance','storage') OR target_workspace NOT IN ('finance','storage') THEN RAISE EXCEPTION 'Invalid cross-workspace link' USING ERRCODE='22023';END IF;IF NOT public.has_permission('finance.workspace.access') OR NOT public.has_permission('storage.workspace.access') THEN RAISE EXCEPTION 'Both workspace permissions are required' USING ERRCODE='42501';END IF;INSERT INTO public.finance_storage_links(source_workspace,source_type,source_id,target_workspace,target_type,target_id,link_type,idempotency_key,created_by)VALUES(source_workspace,source_type,source_id,target_workspace,target_type,target_id,link_type,idempotency_key,auth.uid())ON CONFLICT(idempotency_key)DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING * INTO saved;RETURN saved;END;$$;
REVOKE ALL ON FUNCTION public.link_finance_storage_resource(text,text,uuid,text,text,uuid,text,text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION public.link_finance_storage_resource(text,text,uuid,text,text,uuid,text,text) TO authenticated;
COMMIT;
